compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableTelemetry: 0

nodeLinker: node-modules

npmAuthToken: "${NODE_AUTH_TOKEN-''}"

npmRegistryServer: "https://registry.npmjs.org"
